### ISSUE TITLE
缺少main_AGAIN.py

### ISSUE THREAD

**Issue by ghjksnsi** [JiarenX/AGAIN#1]
作者您好，我对您的论文Adversarially regularized graph attention networks for inductive learning on partially labeled graphs 十分感兴趣，但是在运行代码时发现其中少了main_AGAIN.py这个文件，您可以提供一下吗？谢谢

**Comment by JiarenX** [comment]
Hi,

Thanks for your interest in our work! 

The missing file "main_AGAIN.py" has been added to this repository. Please have a check!

**Comment by JiarenX** [comment]
File uploaded.

**Comment by JiarenX** [comment]
Hi,

Thanks for your interest in our work!

The missing file "main_AGAIN.py" has been added to this repository. Please have a check!
